### ISSUE TITLE
invidious does not build with crystal 1.2.2 or crystal 1.2.3

### ISSUE THREAD

**Issue by GauthierPLM** [iv-org/invidious#2949]
Both versions of crystal fail to build using crystal 1.2.2 and 1.3.2 on Ubuntu 20.04.4 LTS with the following error:

```
Error target invidious failed to compile:
Showing last frame. Use --error-trace for full trace.

In src/invidious/routes/playlists.cr:227:23

 227 | if !plid || !plid.starts_with?("IV")
                         ^-----------
Error: undefined method 'starts_with?' for Array(String) (compile-time type is (Array(String) | Bool | Float64 | Int32 | Int64 | Invidious::User | Preferences | String))
```

Attached are the detailed logs with `--error-trace` option.

[invidious-build-error.txt](https://github.com/iv-org/invidious/files/8172875/invidious-build-error.txt)

**Comment by unixfox** [comment]
Please see https://github.com/iv-org/invidious/issues/2927
